### PR TITLE
Erie 2016 XLS

### PR DESCRIPTION
**Pull request by tsmo4**
Wish I could take credit, it’s on the website now.

### CODE REVIEW

**Comment by dwillis** [comment]
Thanks, @tsmo4. We just added it a few days ago.

**Comment by tsmo4** [comment]
My fork must be behind, I see the 2016 pdf but not the excel.  

Either way, I'll process it today if it hasn't been done yet.

**Comment by dwillis** [comment]
Huh, you're right. Thanks for grabbing this, and for working on it!

**Comment by tsmo4** [comment]
I've got this mostly cleaned up.  Is there a style guide kicking around?  Column names,  party abbreviations, etc?  And are we rolling up write-ins, or keeping the 20+ in NY seperate?

**Comment by dwillis** [comment]
Column names should match those found [in this example](https://github.com/openelections/openelections-data-or/blob/master/2016/20161108__or__general__morrow__precinct.csv). In terms of party abbreviations, just use what's in the source file. You can roll-up write-ins into a single column per precinct, thanks!

**Pull request merged**
